# yaml-language-server: $schema=https://json.schemastore.org/mocharc.json
exit: true
extension: ['ts']
recursive: true
reporter: dot
require:
- ts-node/register/transpile-only
slow: 10000
timeout: 10000
bail: true
forbid-only: true
forbid-pending: true
# parallel: true
